image: "mcr.microsoft.com/dotnet/sdk:7.0"

variables:
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
   DOTNET_CLI_TELEMETRY_OPTOUT: "true"

before_script:
   - dotnet restore

stages:
   - build
   - test

build:
   stage: build
   tags:
       - shared-fi
   script:
       - dotnet build --configuration Release

test:
   stage: test
   tags:
       - shared-fi
   script:
       - dotnet test --configuration Release